import type { ComponentType } from "react";
import dynamic from "next/dynamic";

// GENERATED FILE -- do not hand-edit.
// Regenerated by scripts/generate-addin-page-registry.mjs (a prebuild step) from
// every installed pack's manifest.json pages[]. Re-run `npm run build` (or trigger
// a rebuild from the addins UI) after installing or updating a pack.

export const ADDIN_PAGES: Record<string, Record<string, ComponentType>> = {
};
