/**
 * Delegation types — shared types for the chair → worker delegation flow.
 *
 * Phase 1: sync delegation, text outputs only. These types are the contract
 * between task-extractor.ts, delegation-dispatcher.ts, board-synthesizer.ts,
 * and motherboard-chat.ts.
 *
 * See planning/delegation-architecture.md for the full design.
 */

/**
 * The kind of output a worker is expected to produce. Drives execution mode
 * selection (Phase 1 only uses text generation; structured/action modes are
 * Phase 2/3).
 */
export type OutputType =
  | "document"
  | "analysis"
  | "checklist"
  | "structured_data"
  | "code"
  | "real_world_action";

/**
 * A single actionable task extracted from a chair's prose response that should
 * be delegated to a worker agent. Generated by extractDelegatableTasks().
 */
export interface DelegatableTask {
  /** UUID, generated by the extractor. */
  task_id: string;
  /** What the worker should produce. */
  description: string;
  /** agent_id from chair.worker_agents[] — the worker assigned to this task. */
  assigned_worker_id: string;
  /** The kind of deliverable expected. */
  expected_output_type: OutputType;
  /** What "done" looks like for this task. */
  expected_output_description: string;
  /** Relevant excerpt from chair reasoning + request context. */
  context: string;
  /** task_ids this task waits on (empty = can run in parallel). */
  depends_on: string[];
  /** Which chair proposed this task. */
  source_chair_id: string;
  /** Quote from the chair response that motivated this task. */
  source_excerpt: string;
}

/**
 * The result of a worker executing a delegated task. Produced by
 * dispatchTasks(). One per DelegatableTask.
 */
export interface WorkerDeliverable {
  task_id: string;
  worker_agent_id: string;
  worker_name: string;
  output_type: OutputType;
  /** The deliverable content (or error message if failed). */
  output: string;
  status: "completed" | "failed" | "skipped";
  /** Present if status is "failed". */
  error?: string;
  source_chair_id: string;
  /** ISO timestamp when execution started. */
  started_at: string;
  /** ISO timestamp when execution completed (or failed). */
  completed_at: string;
}

/**
 * A compact summary of a deliverable for inclusion in the board chat result.
 * The full output remains in the job store; this is what the operator sees in
 * the synthesis.
 */
export interface DeliverableSummary {
  task_id: string;
  worker_name: string;
  output_type: OutputType;
  status: "completed" | "failed" | "skipped";
  /** First N chars of output, or the error message. */
  excerpt: string;
  /** true if the full output is stored in the job store. */
  full_output_available: boolean;
}

/**
 * The aggregate result of a delegation cycle — returned to the board chat flow
 * for inclusion in the job response and synthesis.
 */
export interface DelegationResult {
  /** Number of tasks extracted from chair responses. */
  tasks_extracted: number;
  /** Number of tasks dispatched to workers (excludes skipped). */
  tasks_dispatched: number;
  /** One deliverable per task (completed, failed, or skipped). */
  deliverables: WorkerDeliverable[];
  /** Human-readable summary of what was delegated and what happened. */
  summary: string;
}

/**
 * A worker agent as resolved from the blueprint, in the shape the extractor and
 * dispatcher need. Mirrors BlueprintWorkerAgent from agent-job-runner.ts but
 * kept local to the delegation module so it has no dependency on the runner's
 * internal types.
 */
export interface DelegationWorkerAgent {
  agent_id: string;
  name: string;
  domain: string;
  task_scope: string[];
  labor_commons_ref: string | null;
  model?: string;
}

/**
 * A chair response in the shape the extractor needs. Built from the
 * ChairConsultResult produced by the board chat flow.
 */
export interface DelegationChairResponse {
  chair_id: string;
  chair_name: string;
  domain: string;
  response_text: string;
}